name: forex_currency_conversion
description: A Flutter Package for real-time forex prices and conversions.
version: 0.6.5+1
repository: https://github.com/Macacoazul01/forex_currency_conversion

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
